theme = "kanagawa-custom"

[editor]
auto-pairs = false
bufferline = "multiple"
color-modes = true
completion-replace = true
idle-timeout = 1000
mouse = false
middle-click-paste = false
preview-completion-insert = false
scrolloff = 999
scroll-lines = 1
true-color = true
insert-final-newline = true
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "version-control",
]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.lsp]
# enable = false
display-signature-help-docs = true
display-messages = true
display-progress-messages = true
snippets = false
display-inlay-hints = false

[editor.file-picker]
hidden = false
git-ignore = true

[editor.soft-wrap]
enable = true

[keys.normal]
A-q = ":toggle gutters.line-numbers.min-width 110 3"
A-w = ":buffer-close"
C-t = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-v = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-r = ":lsp-restart"
C-i = ":toggle lsp.display-inlay-hints"

[keys.select]
A-q = ":toggle gutters.line-numbers.min-width 110 3"
C-t = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-v = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-r = ":lsp-restart"
C-i = ":toggle lsp.display-inlay-hints"

[keys.insert]
A-q = ":toggle gutters.line-numbers.min-width 110 3"
C-r = ":lsp-restart"
C-i = ":toggle lsp.display-inlay-hints"
