[language-server.rust-analyzer.config]
rust-analyzer.cargo.autoreload = true
rust-analyzer.cargo.sysroot = "discover"
rust-analyzer.rustc.source = "discover"
rust-analyzer.check.command = "clippy"
rust-analyzer.rustfmt.rangeFormatting.enable = true
rust-analyzer.lru.capacity = 1024

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
auto-format = true
